
package inicial;

import clientes.iFclientes;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import usuarios.iFusuarios;
import estabelecimentos.iFestabelecimentos;
import movimentos.iFmovimentos;
import produtos.iFprodutos;


public class jFSisCMP extends javax.swing.JFrame {

    /** Creates new form jFSisCMP */
    public jFSisCMP() {
        initComponents();
        this.setExtendedState(jFSisCMP.MAXIMIZED_BOTH);  
    }

    /** This method is ca   lled from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMpesquisa = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMusuario = new javax.swing.JMenuItem();
        jMcliente = new javax.swing.JMenuItem();
        jMproduto = new javax.swing.JMenuItem();
        jMestabelecimento = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMpesquisa.setText("Pesquisa");
        jMpesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMpesquisaMousePressed(evt);
            }
        });
        jMenuBar1.add(jMpesquisa);

        jMenu1.setText("Cadastros");

        jMusuario.setText("Cad. Usuários");
        jMusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMusuarioMousePressed(evt);
            }
        });
        jMenu1.add(jMusuario);

        jMcliente.setText("Cad. Clientes");
        jMcliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMclienteMousePressed(evt);
            }
        });
        jMenu1.add(jMcliente);

        jMproduto.setText("Cad. Produtos");
        jMproduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMprodutoMousePressed(evt);
            }
        });
        jMenu1.add(jMproduto);

        jMestabelecimento.setText("Cad. Estabelecimentos");
        jMestabelecimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMestabelecimentoMousePressed(evt);
            }
        });
        jMenu1.add(jMestabelecimento);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMusuarioMousePressed
        // TODO add your handling code here:
        iFusuarios iFusu = new iFusuarios();
        jDescritorio.add(iFusu);
        iFusu.show();
    }//GEN-LAST:event_jMusuarioMousePressed

    private void jMclienteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMclienteMousePressed
        // TODO add your handling code here:
        iFclientes iFcli = new iFclientes();
        jDescritorio.add(iFcli);
        iFcli.show();
    }//GEN-LAST:event_jMclienteMousePressed

    private void jMestabelecimentoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMestabelecimentoMousePressed
        // TODO add your handling code here:
        iFestabelecimentos iFest = new iFestabelecimentos();
        jDescritorio.add(iFest);
        iFest.show();
    }//GEN-LAST:event_jMestabelecimentoMousePressed

    private void jMprodutoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMprodutoMousePressed
        // TODO add your handling code here:
        iFprodutos iFpro = null;
        try {
            iFpro = new iFprodutos();
        } catch (SQLException ex) {
            Logger.getLogger(jFSisCMP.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDescritorio.add(iFpro);
        iFpro.show();
        
    }//GEN-LAST:event_jMprodutoMousePressed

    private void jMpesquisaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMpesquisaMousePressed
        // TODO add your handling code here:
        iFmovimentos iFmov = null;
        try {
            iFmov = new iFmovimentos();
        } catch (SQLException ex) {
            Logger.getLogger(jFSisCMP.class.getName()).log(Level.SEVERE, null, ex);
        }
        jDescritorio.add(iFmov);
        iFmov.show();
    }//GEN-LAST:event_jMpesquisaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFSisCMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFSisCMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFSisCMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFSisCMP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new jFSisCMP().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDescritorio;
    private javax.swing.JMenuItem jMcliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMestabelecimento;
    private javax.swing.JMenu jMpesquisa;
    private javax.swing.JMenuItem jMproduto;
    private javax.swing.JMenuItem jMusuario;
    // End of variables declaration//GEN-END:variables
}
