
package clientes;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

public class iFclientes extends javax.swing.JInternalFrame {

    /** Creates new form iFclientes */
    public iFclientes() {
        initComponents();
        telaInicial();          
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTrua = new javax.swing.JTextField();
        jTpesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTnum = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTtel = new javax.swing.JFormattedTextField();
        jTcep = new javax.swing.JFormattedTextField();
        jTcpf = new javax.swing.JFormattedTextField();
        jTdtNasc = new javax.swing.JFormattedTextField();
        jTrenda = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jBnovo = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jBremover = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Clientes");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("ID");

        jLabel2.setText("Nome:");

        jLabel4.setText("Rua:");

        jTpesquisa.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jTpesquisa.setForeground(new java.awt.Color(153, 153, 153));
        jTpesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTpesquisaMouseClicked(evt);
            }
        });
        jTpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTpesquisaKeyReleased(evt);
            }
        });

        jLabel5.setText("Pesquisa");

        jLabel3.setText("CPF:");

        jLabel6.setText("Data de nascimento:");

        jLabel7.setText("Renda:");

        jLabel8.setText("Número:");

        jLabel9.setText("CEP:");

        jLabel10.setText("Telefone:");

        try {
            jTtel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTdtNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTnome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(493, 493, 493))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTdtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jTrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTrua))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTnum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jTcep, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jTtel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(272, 272, 272)))
                .addGap(15, 15, 15))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTcpf, jTdtNasc, jTrenda});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTdtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTcpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTtel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabela);

        jBnovo.setText("Novo");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jBsalvar.setText("Salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBalterar.setText("Alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBremover.setText("Remover");
        jBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBremoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jBnovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBalterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBremover)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(10, 10, 10))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBalterar, jBnovo, jBremover, jBsalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBnovo)
                    .addComponent(jBsalvar)
                    .addComponent(jBalterar)
                    .addComponent(jBremover))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpesquisaKeyReleased
        // TODO add your handling code here:
        String ler = jTpesquisa.getText();
        String sql = "select * from tbclientes where nome like '"+ler+"%'";
        buscaDados(sql);
    }//GEN-LAST:event_jTpesquisaKeyReleased

    private void jTpesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTpesquisaMouseClicked
        // TODO add your handling code here:
        telaInicial();
        jTpesquisa.setText("");
        jTpesquisa.requestFocus();
        jTpesquisa.setForeground(Color.black);        
        String sql = "select * from tbclientes";
        buscaDados(sql);
    }//GEN-LAST:event_jTpesquisaMouseClicked

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
        novo();
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        if (jTnome.getText().equals("") || jTcpf.getText().equals("") 
              || jTdtNasc.getText().equals("") || jTrenda.getText().equals("")
              || jTrua.getText().equals("") || jTnum.getText().equals("") 
              || jTcep.getText().equals("")){           
           JOptionPane.showMessageDialog(null, "Campo obrigatório vazio!");
        } else if (!"".equals(jTcpf.getText())){
            clientes cli = new clientes();
            cli.setNome(jTcpf.getText());
            clientesDAO dao = new clientesDAO();
            try {
                dao.verificar(cli);
                if (!"".equals(cli.getCpf())){
                  JOptionPane.showMessageDialog(null,"Cliente já cadastrado!");
                  jTcpf.setText("");
                  jTcpf.requestFocus();
                }else{                   
                    cli.setNome(jTnome.getText());
                    cli.setCpf(jTcpf.getText());
                    SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");  
                    java.sql.Date data = null;
                    try {
                        data = new java.sql.Date(format.parse(jTdtNasc.getText()).getTime());
                    } catch (ParseException ex) {
                        Logger.getLogger(iFclientes.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    cli.setDataNasc(data); 
                    cli.setRenda(Float.parseFloat(jTrenda.getText()));
                    cli.setRua(jTrua.getText()); 
                    cli.setNum(jTnum.getText());
                    cli.setCep(jTcep.getText());
                    cli.setTel(jTtel.getText());                                               
                try {
                    dao.adicionar(cli);
                }catch (SQLException ex) {
                    Logger.getLogger(iFclientes.class.getName()).log(Level.SEVERE, null, ex);
                }
                    telaInicial();
                }
            } catch (SQLException ex) {
                Logger.getLogger(iFclientes.class.getName()).log(Level.SEVERE, null, ex);
            }           
        }
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // TODO add your handling code here:
        if (jTid.getText().equals("")|| jTnome.getText().equals("")||
           jTcpf.getText().equals("")|| jTrua.getText().equals("")){           
           JOptionPane.showMessageDialog(null, "Campo Obrigatório Vazio");
        } else {
            clientes cli = new clientes();
            cli.setId(Integer.parseInt(jTid.getText())); 
            cli.setNome(jTnome.getText());
            cli.setCpf(jTcpf.getText());
            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = null;
            try {
              data = new java.sql.Date(format.parse(jTdtNasc.getText()).getTime());
                } catch (ParseException ex) {
                        Logger.getLogger(iFclientes.class.getName()).log(Level.SEVERE, null, ex);
               }
            cli.setDataNasc(data); 
            cli.setRenda(Float.parseFloat(jTrenda.getText()));
            cli.setRua(jTrua.getText()); 
            cli.setNum(jTnum.getText());
            cli.setCep(jTcep.getText());
            cli.setTel(jTtel.getText());
            clientesDAO dao = new clientesDAO();
          try {
                dao.alterar(cli);                
          } catch (SQLException ex) {
                Logger.getLogger(iFclientes.class.getName()).log(Level.SEVERE, null, ex);
          }            
            telaInicial();
          }
    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBremoverActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this,"Deseja realmente excluir esse Cliente?",
                "Confirmação",JOptionPane.YES_NO_OPTION);
        if(resp==JOptionPane.YES_NO_OPTION){
                 
           clientes cli = new clientes();
            
           cli.setId(Integer.parseInt(jTid.getText()));                

           clientesDAO dao = new clientesDAO();
         
        try {
            dao.remover(cli);            
        } catch (SQLException ex) {
            Logger.getLogger(iFclientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        telaInicial();
        }
    }//GEN-LAST:event_jBremoverActionPerformed
        
    private void telaInicial(){
        jTid.setEnabled(false);
        jTid.setEditable(false);
        jTnome.setEnabled(false);
        jTcpf.setEnabled(false);
        jTdtNasc.setEnabled(false);
        jTrenda.setEnabled(false);
        jTrua.setEnabled(false);
        jTnum.setEnabled(false);
        jTcep.setEnabled(false);
        jTtel.setEnabled(false);
        jBnovo.setEnabled(true);
        jBsalvar.setEnabled(false);
        jBalterar.setEnabled(false);
        jBremover.setEnabled(false);
        jTid.setText("");
        jTnome.setText("");
        jTcpf.setText("");
        jTdtNasc.setText("");
        jTrenda.setText("");
        jTrua.setText("");
        jTnum.setText("");
        jTcep.setText("");
        jTtel.setText("");
        jTcep.setText("");
        jTdtNasc.setText("");
        jTpesquisa.setText("Digite o nome");
        jTpesquisa.setForeground(Color.DARK_GRAY);
        String sql = "select * from tbclientes";
        buscaDados(sql);
}
    
    private void novo(){
        jTnome.setEnabled(true);
        jTcpf.setEnabled(true);
        jTdtNasc.setEnabled(true);
        jTrenda.setEnabled(true);
        jTrua.setEnabled(true);
        jTnum.setEnabled(true);
        jTcep.setEnabled(true);
        jTtel.setEnabled(true);
        jBnovo.setEnabled(false);
        jBsalvar.setEnabled(true);
        jBalterar.setEnabled(false);
        jBremover.setEnabled(false);
        jTid.setText("");
        jTnome.setText("");
        jTcpf.setText("");
        jTdtNasc.setText("");
        jTrenda.setText("");
        jTrua.setText("");
        jTnum.setText("");
        jTcep.setText("");
        jTtel.setText("");
        jTpesquisa.setText("Digite o nome");
        jTpesquisa.setForeground(Color.DARK_GRAY);
        jTnome.requestFocus();
}
    
    private void selecao(){
        jTnome.setEnabled(true);
        jTcpf.setEnabled(true);
        jTdtNasc.setEnabled(true);
        jTrenda.setEnabled(true);
        jTrua.setEnabled(true);
        jTnum.setEnabled(true);
        jTcep.setEnabled(true);
        jTtel.setEnabled(true);
        jBnovo.setEnabled(true);
        jBsalvar.setEnabled(false);
        jBalterar.setEnabled(true);
        jBremover.setEnabled(true);
        jTpesquisa.setText("Digite o nome");
        jTpesquisa.setForeground(Color.DARK_GRAY);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBremover;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JFormattedTextField jTcep;
    private javax.swing.JFormattedTextField jTcpf;
    private javax.swing.JFormattedTextField jTdtNasc;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTnum;
    private javax.swing.JTextField jTpesquisa;
    private javax.swing.JTextField jTrenda;
    private javax.swing.JTextField jTrua;
    private javax.swing.JFormattedTextField jTtel;
    // End of variables declaration//GEN-END:variables

    private clientesTabela cmt;
    
    public TableModel modeloTabela(String sql){
        clientesDAO c = new clientesDAO();
        cmt = new clientesTabela(c.getLista(sql));
        
        return cmt;
    }
    private void buscaDados(String sql) {
        jTabela.setModel(modeloTabela(sql));
        jTabela.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                // evento de clik na tabela
            if (e.getClickCount() > 0) {
                    
                    
                    //carrega dentro da veriavel linha o numero da lina que foi selecionado
                    int linha = jTabela.getSelectedRow();//linha que foi selecionada
                    
                    
                    //pega coluna selecionada e mostra no campo operação
                  jTid.setText(jTabela.getValueAt(linha, 0).toString());
                  jTnome.setText(jTabela.getValueAt(linha, 1).toString());
                  jTcpf.setText(jTabela.getValueAt(linha, 2).toString());
                  jTdtNasc.setText(jTabela.getValueAt(linha, 3).toString());
                  jTrenda.setText(jTabela.getValueAt(linha, 4).toString());
                  jTrua.setText(jTabela.getValueAt(linha, 5).toString());
                  jTnum.setText(jTabela.getValueAt(linha, 6).toString());
                  jTcep.setText(jTabela.getValueAt(linha, 7).toString());
                  jTtel.setText(jTabela.getValueAt(linha, 8).toString());
                  selecao();
                  
                   //para alterações não permitir modificar chave primaria
                    
                 } 
            }
        });
    }
}
