/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * iFusuario.java
 *
 * Created on 13/09/2013, 09:31:46
 */
package produtos;

import conexao.conexaoSisCMP;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Laegleuson
 */
public class iFprodutos extends javax.swing.JInternalFrame {
    private conexaoSisCMP con_cli = new conexaoSisCMP();
    private Integer idMerc;
    
    /** Creates new form iFclientes */
    public iFprodutos() throws SQLException {
        initComponents();
        telaInicial(); 
    }
        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTpreco = new javax.swing.JTextField();
        jTpesquisa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTesp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTobs = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCestab = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabela = new javax.swing.JTable();
        jBnovo = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jBremover = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("ID");

        jLabel2.setText("Nome:");

        jLabel4.setText("Preço");

        jTpesquisa.setFont(new java.awt.Font("Tahoma", 2, 11));
        jTpesquisa.setForeground(new java.awt.Color(153, 153, 153));
        jTpesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTpesquisaMouseClicked(evt);
            }
        });
        jTpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTpesquisaKeyReleased(evt);
            }
        });

        jLabel5.setText("Pesquisa");

        jLabel3.setText("Especificação:");

        jLabel10.setText("Obs:");

        jLabel6.setText("Estabelecimento:");

        jCestab.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTesp, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jTpreco, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTobs, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                            .addComponent(jLabel10)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTnome, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(319, 319, 319)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jCestab, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCestab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTesp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTpreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTobs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabela);

        jBnovo.setText("Novo");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jBsalvar.setText("Salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBalterar.setText("Alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBremover.setText("Remover");
        jBremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBremoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jBnovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBalterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBremover)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBalterar, jBnovo, jBremover, jBsalvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jBnovo)
                    .addComponent(jBsalvar)
                    .addComponent(jBalterar)
                    .addComponent(jBremover))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpesquisaKeyReleased
        // TODO add your handling code here:
        String ler = jTpesquisa.getText();
        String sql = "select * from tbprodutos p, tbmercantil m where p.id_mercantil = m.id"
                + " and p.nome like '"+ler+"%'";
        buscaDados(sql);
    }//GEN-LAST:event_jTpesquisaKeyReleased

    private void jTpesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTpesquisaMouseClicked
        // TODO add your handling code here:
        telaInicial();
        jTpesquisa.setText("");
        jTpesquisa.requestFocus();
        jTpesquisa.setForeground(Color.black);        
        String sql = "select *,m.nome as nm_mercantil from tbprodutos p, tbmercantil m where p.id_mercantil = m.id";
        buscaDados(sql);
    }//GEN-LAST:event_jTpesquisaMouseClicked

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
        novo();
    }//GEN-LAST:event_jBnovoActionPerformed
    
    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        selJCestab();
        if (jTnome.getText().equals("") || jTesp.getText().equals("") 
          || jTpreco.getText().equals("") || jCestab.getSelectedItem() == null){           
           JOptionPane.showMessageDialog(null, "Campo obrigatório vazio!");
        } else if (!"".equals(jTnome.getText())){
            produtos pro = new produtos();
            pro.setNome(jTnome.getText());
            pro.setEspecificacao(jTesp.getText());
            pro.setId_merc(idMerc);
            produtosDAO dao = new produtosDAO();
            try {
                dao.verificar(pro);
                if (!"".equals(pro.getNome())){
                  JOptionPane.showMessageDialog(null,"Produto já cadastrado!");
                  jTnome.setText("");
                  jTnome.requestFocus();
                }else{                   
                    pro.setNome(jTnome.getText());
                    pro.setEspecificacao(jTesp.getText());
                    pro.setId_merc(idMerc);
                    pro.setPreco(Float.parseFloat(jTpreco.getText())); 
                    pro.setObs(jTobs.getText());                                                                   
                try {
                    dao.adicionar(pro);
                }catch (SQLException ex) {
                    Logger.getLogger(iFprodutos.class.getName()).log(Level.SEVERE, null, ex);
                }
                    telaInicial();
                }
            } catch (SQLException ex) {
                Logger.getLogger(iFprodutos.class.getName()).log(Level.SEVERE, null, ex);
            }           
        }
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // TODO add your handling code here:
        selJCestab();
        if (jTid.getText().equals("")|| jTnome.getText().equals("")||
           jTpreco.getText().equals("") || jCestab.getSelectedItem() == null){           
           JOptionPane.showMessageDialog(null, "Campo Obrigatório Vazio");
        } else {
            produtos pro = new produtos();
            pro.setId(Integer.parseInt(jTid.getText()));
            pro.setNome(jTnome.getText());
            pro.setEspecificacao(jTesp.getText());
            pro.setId_merc(idMerc);
            pro.setPreco(Float.parseFloat(jTpreco.getText())); 
            pro.setObs(jTobs.getText());
            produtosDAO dao = new produtosDAO();
          try {
                dao.alterar(pro);                
          } catch (SQLException ex) {
                Logger.getLogger(iFprodutos.class.getName()).log(Level.SEVERE, null, ex);
          }            
            telaInicial();
          }
    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBremoverActionPerformed
        // TODO add your handling code here:
        int resp = JOptionPane.showConfirmDialog(this,"Deseja realmente excluir esse Produto?",
                "Confirmação",JOptionPane.YES_NO_OPTION);
        if(resp==JOptionPane.YES_NO_OPTION){
                 
           produtos pro = new produtos();
            
           pro.setId(Integer.parseInt(jTid.getText()));                

           produtosDAO dao = new produtosDAO();
         
        try {
            dao.remover(pro);            
        } catch (SQLException ex) {
            Logger.getLogger(iFprodutos.class.getName()).log(Level.SEVERE, null, ex);
        }
        telaInicial();
        }
    }//GEN-LAST:event_jBremoverActionPerformed
   
    private void selJCestab(){
        con_cli.getConexao();
        con_cli.executeSQL("select id from tbmercantil where nome ='" + jCestab.getSelectedItem() + "'");   
        try {
            if (con_cli.resultset.next()){
            idMerc = con_cli.resultset.getInt("id");
            }
        } catch (SQLException ex) {
            Logger.getLogger(iFprodutos.class.getName()).log(Level.SEVERE, null, ex);
        }              
    }
       
    private void telaInicial(){
        jTid.setEnabled(false);
        jTid.setEditable(false);
        jTnome.setEnabled(false);
        jCestab.setEnabled(false);
        jTesp.setEnabled(false);
        jTpreco.setEnabled(false);
        jTobs.setEnabled(false);
        jBnovo.setEnabled(true);
        jBsalvar.setEnabled(false);
        jBalterar.setEnabled(false);
        jBremover.setEnabled(false);
        jTid.setText("");
        jTnome.setText("");
        setComboEstab();
        idMerc = null;
        jTesp.setText("");
        jTpreco.setText("");
        jTobs.setText("");
        jTpesquisa.setText("Digite o nome");
        jTpesquisa.setForeground(Color.DARK_GRAY);
        String sql = "select *,m.nome as nm_mercantil from tbprodutos p, tbmercantil m where p.id_mercantil = m.id";
        buscaDados(sql);
}
    
    private void novo(){
        jTnome.setEnabled(true);
        jCestab.setEnabled(true);
        jTesp.setEnabled(true);
        jTpreco.setEnabled(true);
        jTobs.setEnabled(true);
        jBnovo.setEnabled(false);
        jBsalvar.setEnabled(true);
        jBalterar.setEnabled(false);
        jBremover.setEnabled(false);
        jTid.setText("");
        jTnome.setText("");
        setComboEstab();
        idMerc = null;
        jTesp.setText("");
        jTpreco.setText("");
        jTobs.setText("");
        jTpesquisa.setText("Digite o nome");
        jTpesquisa.setForeground(Color.DARK_GRAY);
        jTnome.requestFocus();
}
    
    private void selecao(){
        jTnome.setEnabled(true);
        jCestab.setEnabled(true);
        jTesp.setEnabled(true);
        jTpreco.setEnabled(true);
        jTobs.setEnabled(true);
        jBnovo.setEnabled(true);
        jBsalvar.setEnabled(false);
        jBalterar.setEnabled(true);
        jBremover.setEnabled(true);
        jTpesquisa.setText("Digite o nome");
        jTpesquisa.setForeground(Color.DARK_GRAY);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBremover;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JComboBox jCestab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabela;
    private javax.swing.JTextField jTesp;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTnome;
    private javax.swing.JTextField jTobs;
    private javax.swing.JTextField jTpesquisa;
    private javax.swing.JTextField jTpreco;
    // End of variables declaration//GEN-END:variables

    private produtosTabela cmt;
    
    public TableModel modeloTabela(String sql){
        produtosDAO c = new produtosDAO();
        cmt = new produtosTabela(c.getLista(sql));
        
        return cmt;
    }
    private void buscaDados(String sql) {
        jTabela.setModel(modeloTabela(sql));
        jTabela.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                super.mouseClicked(e);
                // evento de clik na tabela
            if (e.getClickCount() > 0) {
                    
                    
                    //carrega dentro da veriavel linha o numero da lina que foi selecionado
                    int linha = jTabela.getSelectedRow();//linha que foi selecionada
                    
                    
                    //pega coluna selecionada e mostra no campo operação
                  jTid.setText(jTabela.getValueAt(linha, 0).toString());
                  jTnome.setText(jTabela.getValueAt(linha, 1).toString());
                  jCestab.setSelectedItem(jTabela.getValueAt(linha, 3).toString());
                  jTesp.setText(jTabela.getValueAt(linha, 4).toString());
                  jTpreco.setText(jTabela.getValueAt(linha, 5).toString());
                  jTobs.setText(jTabela.getValueAt(linha, 6).toString());
                  selecao();
                  
                   //para alterações não permitir modificar chave primaria
                    
                 } 
            }
        });
    }
    
    private void setComboEstab() {
        jCestab.removeAllItems();
        con_cli.getConexao();
        con_cli.executeSQL("select * from tbmercantil order by nome");
        try {
            while (con_cli.resultset.next()){
                jCestab.addItem(con_cli.resultset.getString("nome"));                
            }
        } catch (SQLException ex) {
        }
        try {
            con_cli.getConexao().close();
        } catch (SQLException ex) {
            Logger.getLogger(iFprodutos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
